const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
async function getData(){return fetch('/submission.json').then(r=>{if(!r.ok)throw new Error('Submission data unavailable');return r.json()})}
function label(k){return k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}
function moneyTone(k,v,mode='schedule'){if(v<0)return 'bad';if(mode==='flow')return v>0?'good':'';if(mode==='liabilities')return /closingEquity|totalLiabilitiesAndEquity/i.test(k)?'':'bad';if(mode==='assets')return '';if(/revenue|collections|profit|newBorrowing|customerCash/i.test(k))return 'good';if(/expense|cost|cogs|paid|purchase|writeOff|depreciation|distribution|repaid|payable|loan|liabilit/i.test(k))return 'bad';return ''}
function rows(obj,mode='schedule'){return Object.entries(obj).filter(([,v])=>typeof v==='number').map(([k,v])=>`<tr class="${/total|grossProfit|netProfit|operatingProfit|closingCash|netChange/i.test(k)?'total':''}"><td>${label(k)}</td><td class="num ${moneyTone(k,v,mode)}">${euro(v)}</td></tr>`).join('')}
async function renderMain(){const d=await getData(),s=d.statements;
 document.querySelector('#heroProfit').textContent=euro(s.profitAndLoss.netProfit);document.querySelector('#heroCash').textContent=euro(s.cashFlow.closingCash);document.querySelector('#heroAssets').textContent=euro(s.balanceSheet.assets.totalAssets);
 document.querySelector('#pnlTable').innerHTML=rows(s.profitAndLoss,'flow');document.querySelector('#cashTable').innerHTML=rows(s.cashFlow,'flow');document.querySelector('#assetsTable').innerHTML=rows(s.balanceSheet.assets,'assets');document.querySelector('#liabTable').innerHTML=rows({...s.balanceSheet.liabilities,...s.balanceSheet.equity,totalLiabilitiesAndEquity:s.balanceSheet.totalLiabilitiesAndEquity},'liabilities');
 document.querySelector('#checks').innerHTML=d.reconciliations.map(x=>`<div class="card check"><span class="status ${x.status.includes('uncertainty')?'warn':''}" aria-hidden="true">${x.status==='pass'?'✓':'!'}</span><div><b>${x.name}</b><div class="evidence">${x.formula}</div></div></div>`).join('');
 document.querySelector('#uncertainties').innerHTML=[...d.uncertainties.map(x=>`<article class="card uncertainty"><span class="tag material">Open uncertainty</span><h3>${x.issue}</h3><p><b>Provisional treatment:</b> ${x.provisionalTreatment}</p><p><b>Alternative:</b> ${x.alternative}</p><p><b>Required evidence:</b> ${x.requiredEvidence}</p><p><b>Valuation effect:</b> ${x.valuationEffect}</p></article>`),...d.resolvedJudgments.map(x=>`<article class="card uncertainty"><span class="tag">Judgment applied</span><h3>${x.issue}</h3><p><b>Selected basis:</b> ${x.decision}</p><p><b>Reason:</b> ${x.basis}</p></article>`)].join('');
 document.querySelector('#bridge').innerHTML=Object.entries(d.schedules.managementProfitBridge).map(([k,v])=>`<div class="bridge-step ${v<0?'negative':'positive'}"><small>${label(k)}</small><b>${euro(v)}</b></div>`).join('');
 const scheduleNames={revenueReceivables:'Revenue & receivables',inventoryCogs:'Inventory & COGS',payroll:'Payroll',supplierPayables:'Suppliers',ppe:'PPE & depreciation',debtInterest:'Debt & interest',equityDistributions:'Equity & distributions'};
 document.querySelector('#schedules').innerHTML=Object.entries(scheduleNames).map(([key,name])=>`<article class="card schedule-card"><h3>${name}</h3><table><tbody>${rows(d.schedules[key])}</tbody></table>${d.schedules[key].depreciationBasis?`<p class="evidence"><b>Basis:</b> ${d.schedules[key].depreciationBasis}</p>`:''}${d.schedules[key].verificationNeeded?`<p class="evidence"><b>Verification needed:</b> ${d.schedules[key].verificationNeeded}</p>`:''}</article>`).join('');
 document.querySelector('#causes').innerHTML=d.boardRecommendation.causes.map(x=>`<div>${x}</div>`).join('');document.querySelector('#actions').innerHTML=d.boardRecommendation.actions.map(x=>`<li>${x}</li>`).join('');
 const list=document.querySelector('#decisionList');function draw(){const tier=document.querySelector('[data-filter].active').dataset.filter,q=document.querySelector('#search').value.toLowerCase(),category=document.querySelector('#category').value,confidence=document.querySelector('#confidence').value;const items=d.decisions.filter(x=>(tier==='all'||x.reviewTier===tier)&&(category==='all'||x.category===category)&&(confidence==='all'||x.confidence===confidence)&&JSON.stringify(x).toLowerCase().includes(q));document.querySelector('#resultCount').textContent=`${items.length} decisions shown`;list.innerHTML=items.map(x=>`<article id="${x.id}" class="card decision ${x.reviewTier==='material_judgment'?'material':''}"><div class="decision-head"><div><span class="id"><a href="#${x.id}">${x.id}</a> · ${x.category.replaceAll('_',' ')}</span><h3>${x.question}</h3></div><span class="tag ${x.reviewTier==='material_judgment'?'material':''}">${x.reviewTier==='material_judgment'?'material judgment':'operational'}</span></div><p>${x.answer}</p><div class="evidence"><b>Evidence:</b> ${x.evidence.join(' · ')} · <b>Confidence:</b> ${x.confidence}</div><div class="locator"><b>Source locator:</b> ${x.sourceLocator}</div>${x.studentReasoning?`<div class="reason"><b>My reasoning:</b> ${x.studentReasoning}</div>`:''}</article>`).join('')}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw()});['search','category','confidence'].forEach(id=>document.querySelector('#'+id).oninput=draw);draw()}
async function renderReview(){const d=await getData(),m=d.decisions.filter(x=>x.reviewTier==='material_judgment'),low=d.decisions.filter(x=>x.confidence==='low');document.querySelector('#reviewKpis').innerHTML=[['Material judgments',m.length],['Low confidence',low.length],['Final decisions',d.decisions.filter(x=>x.certificationStatus==='final').length],['Open uncertainties',d.uncertainties.length]].map(([a,b])=>`<div class="kpi"><b>${b}</b><span>${a}</span></div>`).join('');document.querySelector('#trail').innerHTML=`<div class="trail-row head"><span>ID</span><span>My first answer</span><span>What I checked</span><span>Final answer</span><span>Confidence</span></div>`+m.map(x=>`<div class="trail-row"><b><a href="/#${x.id}">${x.id}</a></b><span>${x.aiProposal}</span><span>${x.independentChallenge}</span><span>${x.answer}${x.changedFromAI?' <b class="bad">OVERRIDE</b>':''}</span><span class="tag ${x.confidence==='low'?'material':''}">${x.confidence}</span></div>`).join('');document.querySelector('#reviewUncertainty').innerHTML=[...d.uncertainties.map(x=>`<article class="card uncertainty"><span class="tag material">Open uncertainty</span><h3>${x.issue}</h3><p><b>Provisional treatment:</b> ${x.provisionalTreatment}</p><p><b>Alternative:</b> ${x.alternative}</p><p><b>Evidence needed:</b> ${x.requiredEvidence}</p><p><b>Valuation effect:</b> ${x.valuationEffect}</p></article>`),...d.resolvedJudgments.map(x=>`<article class="card uncertainty"><span class="tag">Judgment applied</span><h3>${x.issue}</h3><p><b>Selected basis:</b> ${x.decision}</p><p><b>Basis:</b> ${x.basis}</p></article>`)].join('')}
if(document.body.dataset.page==='review')renderReview().catch(showError);else renderMain().catch(showError);function showError(e){document.querySelector('main').insertAdjacentHTML('afterbegin',`<p class="bad">${e.message}</p>`)}

