const euro=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
async function getData(){return fetch('/submission.json').then(r=>{if(!r.ok)throw new Error('Submission data unavailable');return r.json()})}
function rows(obj){return Object.entries(obj).filter(([,v])=>typeof v==='number').map(([k,v])=>`<tr class="${/total|grossProfit|netProfit|operatingProfit|closingCash|netChange/i.test(k)?'total':''}"><td>${k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}</td><td class="num ${v<0?'bad':''}">${euro(v)}</td></tr>`).join('')}
async function renderMain(){const d=await getData(),s=d.statements;
 document.querySelector('#profit').textContent=euro(s.profitAndLoss.netProfit);document.querySelector('#cash').textContent=euro(s.cashFlow.closingCash);document.querySelector('#assets').textContent=euro(s.balanceSheet.assets.totalAssets);
 document.querySelector('#pnlTable').innerHTML=rows(s.profitAndLoss);document.querySelector('#cashTable').innerHTML=rows(s.cashFlow);document.querySelector('#assetsTable').innerHTML=rows(s.balanceSheet.assets);document.querySelector('#liabTable').innerHTML=rows({...s.balanceSheet.liabilities,...s.balanceSheet.equity,totalLiabilitiesAndEquity:s.balanceSheet.totalLiabilitiesAndEquity});
 document.querySelector('#checks').innerHTML=d.reconciliations.map(x=>`<div class="card check"><span class="status ${x.status.includes('uncertainty')?'warn':''}">${x.status==='pass'?'✓':'!'}</span><div><b>${x.name}</b><div class="evidence">${x.formula}</div></div></div>`).join('');
 document.querySelector('#uncertainties').innerHTML=d.uncertainties.map(x=>`<article class="card uncertainty"><span class="tag material">${x.range}</span><h3>${x.issue}</h3><p><b>Cause:</b> ${x.cause}</p><p><b>Treatment:</b> ${x.treatment}</p></article>`).join('');
 document.querySelector('#causes').innerHTML=d.boardRecommendation.causes.map(x=>`<div>${x}</div>`).join('');document.querySelector('#actions').innerHTML=d.boardRecommendation.actions.map(x=>`<li>${x}</li>`).join('');
 const list=document.querySelector('#decisionList');function draw(filter='all',q=''){list.innerHTML=d.decisions.filter(x=>(filter==='all'||x.reviewTier===filter)&&JSON.stringify(x).toLowerCase().includes(q.toLowerCase())).map(x=>`<article class="card decision ${x.reviewTier==='material_judgment'?'material':''}"><div class="decision-head"><div><span class="id">${x.id} · ${x.category.replace('_',' ')}</span><h3>${x.question}</h3></div><span class="tag ${x.reviewTier==='material_judgment'?'material':''}">${x.reviewTier==='material_judgment'?'material judgment':'operational'}</span></div><p>${x.answer}</p><div class="evidence"><b>Evidence:</b> ${x.evidence.join(' · ')} · <b>Confidence:</b> ${x.confidence}</div>${x.studentReasoning?`<div class="reason"><b>Certified reasoning:</b> ${x.studentReasoning}</div>`:''}</article>`).join('')}
 draw();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.filter,document.querySelector('#search').value)});document.querySelector('#search').oninput=e=>draw(document.querySelector('[data-filter].active').dataset.filter,e.target.value)}
async function renderReview(){const d=await getData(),m=d.decisions.filter(x=>x.reviewTier==='material_judgment'),low=d.decisions.filter(x=>x.confidence==='low');document.querySelector('#reviewKpis').innerHTML=[['Material judgments',m.length],['Low confidence',low.length],['Student overrides',m.filter(x=>x.changedFromAI).length],['Open uncertainties',d.uncertainties.length]].map(([a,b])=>`<div class="kpi"><b>${b}</b><span>${a}</span></div>`).join('');document.querySelector('#trail').innerHTML=`<div class="trail-row head"><span>ID</span><span>AI proposal</span><span>Independent challenge</span><span>Final certification</span><span>Confidence</span></div>`+m.map(x=>`<div class="trail-row"><b>${x.id}</b><span>${x.aiProposal}</span><span>${x.independentChallenge}</span><span>${x.answer}${x.changedFromAI?' <b class="bad">OVERRIDE</b>':''}</span><span class="tag ${x.confidence==='low'?'material':''}">${x.confidence}</span></div>`).join('');document.querySelector('#reviewUncertainty').innerHTML=d.uncertainties.map(x=>`<article class="card uncertainty"><h3>${x.issue}</h3><p>${x.cause}</p><span class="tag material">${x.range}</span></article>`).join('')}
if(document.body.dataset.page==='review')renderReview().catch(showError);else renderMain().catch(showError);function showError(e){document.querySelector('main').insertAdjacentHTML('afterbegin',`<p class="bad">${e.message}</p>`)}

